### ISSUE TITLE
fix .yml

### ISSUE THREAD

**Issue by jorgepz** [jorgepz/Julia_Docs_Testbed#1]
```
ERROR: LoadError: ArgumentError: Package Documenter not found in current path:
- Run `import Pkg; Pkg.add("Documenter")` to install the Documenter package.
- ```

**Comment by jorgepz** [comment]
[10] top-level scope
    @ none:1
Error: Process completed with exit code 1.

https://github.com/jorgepz/Julia-LaTeX-testbed/runs/2895434225?check_suite_focus=true

**Comment by jorgepz** [comment]
```ERROR: could not find project file in package at `/home/runner/work/Julia-LaTeX-testbed/Julia-LaTeX-testbed` maybe `subdir` needs to be specified```

**Comment by mforets** [comment]
falta el Project.toml del ExampleA en https://github.com/jorgepz/Julia-LaTeX-testbed/tree/main/ExampleA

**Comment by jorgepz** [comment]
> falta el Project.toml del ExampleA en https://github.com/jorgepz/Julia-LaTeX-testbed/tree/main/ExampleA

gracias! ahi fue un intento que parece q sigue sin andar https://github.com/jorgepz/Julia-LaTeX-testbed/pull/2/checks?check_run_id=2895714830
